Add CD workflows
Catalyst-CI-CD/catalyst-infrastructure pull request #12
Opened 2023-11-10 16:58 UTC by KhaledHegazy222

Provide CD workflows that automates:
- Building Project go binaries
- Creating New Releases on Tags

2023-11-10 18:38 UTC, tareknaser requested changes

2023-11-10 18:38 UTC, tareknaser commented on .goreleaser.yaml
> +# vim: set ts=2 sw=2 tw=0 fo=cnqoj
I don't think these lines are needed.

2023-11-10 18:38 UTC, tareknaser commented on .goreleaser.yaml
> +      - "^test:"
Can you create a file `CHANGELOG.md` in the project's root directory? 
Here is [a good resource](https://keepachangelog.com/en/1.0.0/)

This also assumes that we adhere to some kind of standard for commit messages.
We should discuss this the next standup.

2023-11-10 18:38 UTC, tareknaser commented on .goreleaser.yaml
> +    - go generate ./...
Do we need `go generate`?

2023-11-10 18:38 UTC, tareknaser commented on .github/workflows/release.yml
> +      - "*"
```suggestion
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
```

We don't need CD for other branches
Let's also run CD when there is a new version tag

2023-11-10 19:37 UTC, AbdelrahmanElawady requested changes

2023-11-10 19:37 UTC, AbdelrahmanElawady commented on .github/workflows/release.yml
> +      - main
this will trigger with every push to main which we don't want that we want only on tags

2023-11-10 19:37 UTC, AbdelrahmanElawady commented on .github/workflows/release.yml
> +          go-version: stable
we need to specify which version to use in case we didn't upgrade to the next stable one

2023-11-10 19:37 UTC, AbdelrahmanElawady commented on .github/workflows/release.yml
> +      - run: git fetch --force --tags
why are we running fetch after checkout? the repo should be there already

2023-11-10 19:37 UTC, AbdelrahmanElawady commented on .github/workflows/release.yml
> +      - uses: actions/checkout@v3
v4 is out we should use it if possible

2023-11-10 19:55 UTC, KhaledHegazy222 commented on .github/workflows/release.yml
> +      - main
I think github actions don't have support to directly have the triggers specified on both branch and tags
so I think for a workaround we might do something like this :

```yml
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check if tag starts with "v*"
      run:|
        if [[ ${{ github.ref }} != 'refs/tags/v*' ]]; then
          exit 0
        fi
    
```

what do you think ?

2023-11-10 19:58 UTC, AbdelrahmanElawady commented on .github/workflows/release.yml
> +      - main
Maybe something like this:
```yaml
on:
  push:
    tags:
      - "v*"
```

2023-11-10 20:11 UTC, KhaledHegazy222 commented on .github/workflows/release.yml
> +      - main
@tareknaser mentioned that this will trigger on other branches that has tages already. wouldn't that be a problem ?

2023-11-10 20:19 UTC, AbdelrahmanElawady commented on .github/workflows/release.yml
> +      - main
I think this only triggers when a new tag is created, so only once for that tag. Any new push to the branch shouldn't trigger it, as far as I know. Relevant GitHub [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore)

2023-11-11 12:46 UTC, tareknaser approved these changes
Thanks for putting this together

2023-11-11 12:53 UTC, AbdelrahmanElawady approved these changes
LGTM

2023-11-11 12:58 UTC, merged